name: Check pull request
on:
  pull_request:
    types: [opened, reopened]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test
      - name: Build application
        run: npm run build
