name: Recreate next branch
on: delete
jobs:
  recreate-next:
    if: github.event.ref_type == 'branch' && github.event.ref == 'next'
    name: Recreate next branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Branch and push
        run: |
          git checkout -b next
          git push -u origin next
